makerdao/governance-manual

governance/DssVest Detail.md, governance/How to Use DssVest.md
DssVest Documentation, work in progress and open for feedback. Currently split into traditional documentation and how to guides
=> Dss vest documentation

protocol-status/protocol-and-dao-status.md
Changed to correct link, moved it up the list as it should be more prominent than the older deprecated UIs, updated description
=> Updated SAS unified auctions link and description

parameter-index/collateral-auction/param-max-auction-duration.md
=> Typo changes

module-index/module-flash-mint-module.md
@LongForWisdom @Gala-G  made some updates to Flash Mint Module documentation if anyone has suggestions
=> DRAFT: Updates to Flash Mint Module

SUMMARY.md, delegation/separation-of-powers.md
On staging here: https://longforwisdom.gitbook.io/new-collection/governance/what-is-delegation/separation-of-powers
Plan is to link to this from the voting portal, so that MKR Holders are aware of the risks of delegating to Core Unit Members.
=> Separation of Powers resource for delegate.

SUMMARY.md, delegation/delegate-attract-more-mkr.md, delegation/delegate-metric-tracking.md, delegation/why-to-become-a-recognized-delegate.md
@LongForWisdom @Gala-G 
Added new delegate docs
=> Add new delegate docs

parameter-index/collateral-auction/param-auction-price-function.md, protocol-status/protocol-and-dao-status.md
=> update link address for stairstep exponential image

module-index/module-dai-direct-deposit.md
Adds info about setting `bar` to 0, minor formatting changes, add relative link to DCIAM
=> update D3M docs

module-index/module-dai-direct-deposit.md
Change `MOM` to `DIRECT_MOM` to improve accuracy per PE suggestion
=> improve terminology

protocol-status/protocol-and-dao-status.md
Replaced the old domain for MCD Gov Tracker. Added MCD Vaults Tracker and Data API.
=> added DICU trackers and API

SUMMARY.md, delegation/mkr-holder-how-to-delegate.md, governance/how-to-vote.md, governance/voting-in-makerdao.md
Add review date to how to delegate video
Change How to vote video to own entry
Add review dates
=> Multiple fixes

module-index/module-dciam.md
adds reference link to main debt ceiling article from line entry under DC-IAM
=> add reference link

governance/approval-voting-guide.md
=> Improved Approval Voting Guide

core-units/core-unit-budget-flow.md, core-units/core-units.md, governance/mips.md, protocol-status/acronyms.md, protocol-status/protocol-and-dao-status.md
Maintenance Pass for:
- protocol-status\acronyms.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/acronyms)
- core-units\core-unit-budget-flow.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/core-unit-budget-flow)
- protocol-status\protocol-and-dao-status.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/protocol-and-dao-status)
- core-units\core-units.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/structure/core-units)
- governance\mips.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/structure/mips)
=> Maintenance batch - Overview + Structure

delegation/delegate-attract-more-mkr.md, delegation/delegates-code.md, delegation/recognized-delegate-requirements.md
- Attracting more MKR
- CoC
- Requirements
=> STAGING - Delegation scheduled maintenance

delegation/delegate-metric-tracking.md, delegation/separation-of-powers.md, delegation/what-is-delegation.md
* Delegate metric tracking
* What is delegation?
* Separation of powers
=> STAGING - Delegation regular maintenance

governance/monthly-governance-cycle.md, governance/off-chain-governance.md, governance/weekly-governance-cycle.md
=> DONE: Weekly Cycles + Offchain Governance updates

SUMMARY.md, delegation/why-to-become-a-recognized-delegate.md, governance/on-chain-governance.md, protocol-status/acronyms.md
Staging Links:
[On Chain Governance](https://longforwisdom.gitbook.io/new-collection/governance/voting-in-makerdao/on-chain-governance)
[Why Become a Recognized Delegate?](https://longforwisdom.gitbook.io/new-collection/delegation/for-delegates/why-to-become-a-recognized-delegate)
=> DONE: Review pass for items in governance and delegation sections

delegation/delegate-attract-more-mkr.md, delegation/delegates-code.md, delegation/recognized-delegate-requirements.md
- [Attracting more MKR](https://manual.makerdao.com/delegation/for-delegates/delegate-attract-more-mkr)
- [CoC](https://manual.makerdao.com/delegation/for-delegates/delegates-code)
- [Requierements](https://manual.makerdao.com/delegation/for-delegates/recognized-delegate-requirements)
=> Delegation scheduled maintenance

delegation/delegates-code.md, delegation/recognized-delegate-requirements.md
- Repaired broken HTML entities
- Minor rewording
=> Recognized Delegates: minor fixes and adjustments

delegation/mkr-holder-guide.md, governance/practical-guide-voting.md, parameter-index/core/param-global-debt-ceiling.md
Staging Links:
[MKR Holders Guide to Delegation](https://longforwisdom.gitbook.io/new-collection/delegation/for-mkr-holders/mkr-holder-guide)
[Practical Guide to Voting](https://longforwisdom.gitbook.io/new-collection/governance/voting-in-makerdao/practical-guide-voting)
=> Review pass on delegation and voting items. 

parameter-index/core/param-global-liquidation-limit.md, parameter-index/core/param-gsm-pause-delay.md
Staging links:
- [GSM](https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-gsm-pause-delay)
- [Global Liquidation Limit](https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-global-liquidation-limit)
=> Scheduled Maintenance for Core Parameters

SUMMARY.md, governance/on-chain-governance.md, parameter-index/core/param-dai-savings-rate.md, parameter-index/core/param-global-debt-ceiling.md, parameter-index/core/param-system-surplus-buffer.md
Staging Links:
[Dai Savings Rate](https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-dai-savings-rate)
[Global Debt Ceiling](https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-global-debt-ceiling)
[System Surplus Buffer](https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-system-surplus-buffer)
=> DONE: System Parameter Partial Maintenance Pass

parameter-index/vault-risk/param-debt-ceiling.md
=> STAGING: Debt ceiling doc

parameter-index/collateral-auction/param-auction-price-function.md, parameter-index/collateral-auction/param-auction-price-multiplier.md
=> MOM review

parameter-index/vault-risk/param-liquidation-penalty.md, parameter-index/vault-risk/param-liquidation-ratio.md
- Liquidation Penalty
- Liquidation Ratio
=> Vault Risk Parameters Scheduled Maintenance

parameter-index/vault-risk/param-debt-ceiling.md, parameter-index/vault-risk/param-debt-floor.md, parameter-index/vault-risk/param-rwa-agreement.md
Staging branch link: https://github.com/makerdao/governance-manual/pull/182, https://github.com/makerdao/governance-manual/pull/190
=> DONE: Debt ceiling, debt floor, RWA Agreement

parameter-index/collateral-auction/param-auction-price-function.md, parameter-index/collateral-auction/param-auction-price-multiplier.md
=> DONE: Param-Auction-Price-Function and Param-Auction-Price-Multiplier

parameter-index/debt-auction/param-bid-size.md, parameter-index/debt-auction/param-lot-size-increase.md, parameter-index/debt-auction/param-min-bid-decrease-flop.md
- Bid size
- Lot size increase
- Min bid decrease
=> STAGING: Debt Auction Params scheduled maintenance

parameter-index/collateral-auction/param-flat-kick-incentive.md, parameter-index/collateral-auction/param-local-liquidation-limit.md, parameter-index/collateral-auction/param-proportional-kick-incentive.md
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-local-liquidation-limit
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-flat-kick-incentive
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-proportional-kick-incentive
=> FOR REVIEW: Maintenance pass for collateral auction parameters.

parameter-index/surplus-auction/param-auction-duration-flap.md, parameter-index/surplus-auction/param-bid-duration-flap.md
- Auction duration (flap)
- Bid duration (flap)
=> Surplus Auction Params Scheduled Maintenance

parameter-index/debt-auction/param-bid-duration-flop.md, parameter-index/debt-auction/param-debt-auction-delay.md, parameter-index/debt-auction/param-initial-lot-size.md
Staging links:
- [Flop Bid Duration](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-bid-duration-flop)
- [Debt Auction Delay](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-debt-auction-delay)
- [Initial Lot Size](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-initial-lot-size)
=> FOR REVIEW: Debt Auction Params scheduled maintenance

parameter-index/surplus-auction/param-auction-duration-flap.md, parameter-index/surplus-auction/param-bid-duration-flap.md
Staging links:
- [Auction duration (flap)](https://longforwisdom.gitbook.io/new-collection/parameter-index/surplus-auction/param-auction-duration-flap)
- [Bid duration (flap)](https://longforwisdom.gitbook.io/new-collection/parameter-index/surplus-auction/param-bid-duration-flap)
=> TO REVIEW: Surplus auction params maintenance

parameter-index/collateral-auction/param-max-auction-drawdown.md, parameter-index/collateral-auction/param-max-auction-duration.md
Staging Links:
[Collateral Auction Drawdown](https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-max-auction-drawdown)
[Collateral Auction Duration](https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-max-auction-duration)
=> DONE: Review pass collateral auction drawdown and duration.

governance/gsm-exceptions.md
Added disclaimer and messed around with formatting.
=> STAGING: GSM Exceptions

collateral/collateral-overview.md, delegation/mkr-holder-how-to-delegate.md, governance/approval-voting-guide.md, governance/proposal-bounties.md, governance/voting-in-makerdao.md, module-index/module-emergency-shutdown.md, module-index/module-flash-mint-module.md, module-index/module-lerp.md, module-index/module-psm.md, parameter-index/collateral-auction/param-auction-price-multiplier.md, parameter-index/surplus-auction/param-surplus-auction-limit.md
Didn't bother on staging with this one.
=> FOR REVIEW: Minor fixes

SUMMARY.md, misc/discords.md
https://longforwisdom.gitbook.io/new-collection/makerdao/overview/discords
=> DONE: Added incomplete list of MakerDAO discords

parameter-index/core/param-dai-savings-rate.md
* add etherscan link
* add to considerations section
* update review dates
staging: https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-dai-savings-rate
=> update DSR doc

module-index/module-dai-direct-deposit.md
updated d3m doc with assistance from chatgpt
=> update d3m doc

SUMMARY.md, collateral/monetalis-clydesdale.md
staging: https://longforwisdom.gitbook.io/new-collection/collateral/real-world-assets-in-detail/monetalis-clydesdale
=> add monetalis clydesdale to RWA collaterals

parameter-index/collateral-auction/param-auction-price-multiplier.md, parameter-index/core/param-dai-savings-rate.md, parameter-index/debt-auction/param-bid-duration-flop.md, parameter-index/debt-auction/param-debt-auction-delay.md, parameter-index/debt-auction/param-lot-size-increase.md, parameter-index/debt-auction/param-min-bid-decrease-flop.md, parameter-index/surplus-auction/param-auction-duration-flap.md, parameter-index/surplus-auction/param-bid-duration-flap.md, parameter-index/surplus-auction/param-min-bid-increase-flap.md, parameter-index/surplus-auction/param-surplus-auction-limit.md, parameter-index/surplus-auction/param-surplus-lot-size.md, parameter-index/vault-risk/param-liquidation-penalty.md, parameter-index/vault-risk/param-liquidation-ratio.md, parameter-index/vault-risk/param-stability-fee.md
Also added some detail where appropriate.
=> STAGING: Updated parameter index examples to use unified formatting.

parameter-index/collateral-auction/param-auction-price-multiplier.md, parameter-index/core/param-dai-savings-rate.md, parameter-index/debt-auction/param-auction-duration-flop.md, parameter-index/debt-auction/param-bid-duration-flop.md, parameter-index/debt-auction/param-debt-auction-delay.md, parameter-index/debt-auction/param-lot-size-increase.md, parameter-index/debt-auction/param-min-bid-decrease-flop.md, parameter-index/surplus-auction/param-auction-duration-flap.md, parameter-index/surplus-auction/param-bid-duration-flap.md, parameter-index/surplus-auction/param-min-bid-increase-flap.md, parameter-index/surplus-auction/param-surplus-auction-limit.md, parameter-index/surplus-auction/param-surplus-lot-size.md, parameter-index/vault-risk/param-liquidation-penalty.md, parameter-index/vault-risk/param-liquidation-ratio.md, parameter-index/vault-risk/param-stability-fee.md
https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-dai-savings-rate
https://longforwisdom.gitbook.io/new-collection/parameter-index/vault-risk/param-stability-fee
https://longforwisdom.gitbook.io/new-collection/parameter-index/vault-risk/param-liquidation-ratio
https://longforwisdom.gitbook.io/new-collection/parameter-index/vault-risk/param-liquidation-penalty
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-auction-price-multiplier
https://longforwisdom.gitbook.io/new-collection/parameter-index/surplus-auction/param-surplus-lot-size
https://longforwisdom.gitbook.io/new-collection/parameter-index/surplus-auction/param-min-bid-increase-flap
https://longforwisdom.gitbook.io/new-collection/parameter-index/surplus-auction/param-au …
=> FOR REVIEW: Updated formatting for examples in parameter docs

governance/gsm-exceptions.md
Staging Link: https://longforwisdom.gitbook.io/new-collection/governance/verification/gsm-exceptions
=> FOR REVIEW: Added Debt Ceiling Breaker to GSM exceptions.

governance/off-chain-governance.md
Staging link: https://longforwisdom.gitbook.io/new-collection/governance/off-chain/off-chain-governance
=> FOR REVIEW: Update off-chain-governance.md

parameter-index/surplus-auction/param-surplus-cooldown.md, parameter-index/surplus-auction/param-surplus-slippage-tolerance.md
=> updates based on feedback

parameter-index/core/param-dai-savings-rate.md
Staging: https://longforwisdom.gitbook.io/new-collection/parameter-index/core/param-dai-savings-rate
=> FOR REVIEW: EDSR updates
